# Generated by Django 4.2.6 on 2023-10-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BibEntry",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("csl_data", models.JSONField()),
                ("ref", models.TextField(max_length=1024, null=True)),
                ("indexed", models.BooleanField(default=False)),
            ],
        ),
    ]
