# Generated by Django 4.2.6 on 2023-10-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nederlandse_heidegger_bibliografie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bibentry",
            old_name="csl_data",
            new_name="csl_json",
        ),
        migrations.RenameField(
            model_name="bibentry",
            old_name="ref",
            new_name="reference",
        ),
    ]
