# Generated by Django 4.2.6 on 2023-11-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nederlandse_heidegger_bibliografie",
            "0002_rename_csl_data_bibentry_csl_json_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bibentry",
            name="citations",
            field=models.ManyToManyField(
                related_name="cited_by",
                to="nederlandse_heidegger_bibliografie.bibentry",
            ),
        ),
    ]
