# Generated by Django 4.2.6 on 2023-11-04 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nederlandse_heidegger_bibliografie", "0003_bibentry_citations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibentry",
            name="citations",
        ),
        migrations.AddField(
            model_name="bibentry",
            name="citations",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cited_by",
                to="nederlandse_heidegger_bibliografie.bibentry",
            ),
        ),
    ]
