# Generated by Django 4.2.6 on 2023-11-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nederlandse_heidegger_bibliografie",
            "0004_remove_bibentry_citations_bibentry_citations",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bibentry",
            name="citations",
        ),
        migrations.AddField(
            model_name="bibentry",
            name="citations",
            field=models.ManyToManyField(
                null=True,
                related_name="cited_by",
                to="nederlandse_heidegger_bibliografie.bibentry",
            ),
        ),
    ]
