# Generated by Django 4.2.6 on 2023-11-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nederlandse_heidegger_bibliografie", "0007_bibentry_issued"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bibentry",
            old_name="issued",
            new_name="year_issued",
        ),
    ]
