# Generated by Django 4.2.6 on 2024-08-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nederlandse_heidegger_bibliografie', '0008_rename_issued_bibentry_year_issued'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibentry',
            options={'ordering': ['id']},
        ),
    ]
