# Generated by Django 4.2.6 on 2024-11-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nederlandse_heidegger_bibliografie", "0009_alter_bibentry_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("csl_json", models.JSONField()),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="bibentry",
            name="author",
            field=models.ManyToManyField(
                related_name="works", to="nederlandse_heidegger_bibliografie.author"
            ),
        ),
    ]
