# Generated by Django 4.2.6 on 2024-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nederlandse_heidegger_bibliografie", "0010_author_bibentry_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["family_name", "given_name"],
                "verbose_name": "author",
            },
        ),
        migrations.AlterModelOptions(
            name="bibentry",
            options={"ordering": ["id"], "verbose_name": "bibliography entry"},
        ),
        migrations.AddField(
            model_name="author",
            name="family_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="author",
            name="family_name_affix",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="given_name",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
